# Un-comment if mold is installed
# and check if the path is correct
#[target.x86_64-unknown-linux-gnu]
#linker = "clang"
#rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]


[unstable]
build-std = ["std", "panic_abort"]
build-std-features = []

